# Generated by Django 3.0.7 on 2020-07-04 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProfileRelation',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile_1', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='profile1', to='users.UserProfile')),
                ('user_profile_2', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='profile2', to='users.UserProfile')),
            ],
        ),
    ]
