# Generated by Django 3.0.7 on 2020-07-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200704_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilerelation',
            name='relation_name',
            field=models.CharField(default='son', max_length=100),
            preserve_default=False,
        ),
    ]
