# Generated by Django 3.0.7 on 2020-07-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profilerelation_relation_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profilerelation',
            unique_together={
                ('user_profile_1', 'user_profile_2', 'relation_name')},
        ),
    ]
