# Generated by Django 3.0.7 on 2020-07-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200704_1518'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profilerelation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='profilerelation',
            constraint=models.UniqueConstraint(fields=(
                'user_profile_1', 'user_profile_2', 'relation_name'), name='profile_relations'),
        ),
    ]
