# Generated by Django 3.0.7 on 2020-07-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200704_1522'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profilerelation',
            name='profile_relations',
        ),
        migrations.AddConstraint(
            model_name='profilerelation',
            constraint=models.UniqueConstraint(
                fields=('user_profile_1', 'user_profile_2'), name='profile_relations'),
        ),
    ]
