# Generated by Django 3.0.7 on 2020-07-03 10:27

from django.db import migrations, models
import django.db.models.deletion
import interactions.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfAnswerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('answers', models.TextField(editable=False,
                                             validators=[interactions.validators.json_validator])),
                ('accuracy', models.FloatField(blank=True, null=True,
                                               validators=[interactions.validators.percentage_validator])),
                ('scores', models.TextField(editable=False)),
                ('self_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                        related_name='selfanswergroup_self', to='users.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelationAnswerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('answers', models.TextField(editable=False,
                                             validators=[interactions.validators.json_validator])),
                ('accuracy', models.FloatField(blank=True, null=True,
                                               validators=[interactions.validators.percentage_validator])),
                ('scores', models.TextField(editable=False)),
                ('relation_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                            related_name='relationanswergroup_relation', to='users.UserProfile')),
                ('self_user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                        related_name='relationanswergroup_self', to='users.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
