# Generated by Django 3.0.5 on 2020-06-11 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationquestion',
            name='question_factor',
            field=models.IntegerField(
                choices=[(-1, 'negative'), (1, 'positive')]),
        ),
    ]
