# Generated by Django 3.0.7 on 2020-06-26 06:02

from django.db import migrations, models
import interactions.validators


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationanswergroup',
            name='answers',
            field=models.TextField(validators=[interactions.validators.json_validator]),
        ),
        migrations.AlterField(
            model_name='selfanswergroup',
            name='answers',
            field=models.TextField(validators=[interactions.validators.json_validator]),
        ),
    ]
