# Generated by Django 3.0.5 on 2020-06-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_auto_20200611_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationquestion',
            name='ocean_subclass',
            field=models.CharField(choices=[('openess', 'openess'), ('conscientiousness', 'conscientiousness'), (
                'extraversion', 'extraversion'), ('agreeableness', 'agreeableness'), ('neuroticism', 'neuroticism')], max_length=150),
        ),
        migrations.AlterField(
            model_name='selfquestion',
            name='ocean_subclass',
            field=models.CharField(choices=[('openess', 'openess'), ('conscientiousness', 'conscientiousness'), (
                'extraversion', 'extraversion'), ('agreeableness', 'agreeableness'), ('neuroticism', 'neuroticism')], max_length=150),
        ),
    ]
