# Generated by Django 3.0.7 on 2020-06-26 19:19

from django.db import migrations, models
import interactions.validators


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_auto_20200626_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationanswergroup',
            name='answers',
            field=models.TextField(editable=False, validators=[
                                   interactions.validators.json_validator]),
        ),
        migrations.AlterField(
            model_name='selfanswergroup',
            name='answers',
            field=models.TextField(editable=False, validators=[
                                   interactions.validators.json_validator]),
        ),
    ]
