# Generated by Django 3.0.7 on 2020-07-05 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_globalaverages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationanswergroup',
            name='relation_user_profile',
        ),
        migrations.AddField(
            model_name='relationanswergroup',
            name='attempted_against',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationanswergroup_attempted', to='interactions.SelfAnswerGroup'),
        ),
    ]
