# Generated by Django 3.0.5 on 2020-06-15 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_auto_20200611_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfanswergroup',
            name='user',
        ),
    ]
