# Generated by Django 3.0.5 on 2020-06-15 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200614_1440'),
        ('interactions', '0004_remove_selfanswergroup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationanswergroup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='relationanswergroup',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='relationanswergroup',
            name='relation_user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='users.UserProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationanswergroup',
            name='self_user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='self', to='users.UserProfile'),
            preserve_default=False,
        ),
    ]
