# Generated by Django 3.0.7 on 2020-07-05 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_auto_20200705_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationanswergroup',
            name='relation_user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationanswergroup_relation', to='interactions.SelfAnswerGroup'),
        ),
    ]
