# Generated by Django 3.0.5 on 2020-06-18 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_auto_20200615_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationanswerchoice',
            name='question',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='interactions.RelationQuestion'),
        ),
    ]
