# Generated by Django 3.0.7 on 2020-07-05 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200704_1523'),
        ('interactions', '0005_relationanswergroup_relation_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationanswergroup',
            name='relation_user_profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='relationanswergroup_relation', to='users.UserProfile'),
            preserve_default=False,
        ),
    ]
